/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://hngq7oeolngohesbblbppultui.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jnhuz7r7sjenpn437dim6pwl54",
    "aws_cognito_identity_pool_id": "us-east-2:b8da1cc2-0e29-4bf4-9db7-31306b9b3e09",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_o3feHsn2r",
    "aws_user_pools_web_client_id": "6ka9girmgpanhl8pcffmtoe7fl",
    "oauth": {
        "domain": "dailykpop63b1ff97-63b1ff97-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "dailykpop://,exp://127.0.0.1:19000/--/,https://dailykpop63b1ff97-63b1ff97-dev.auth.us-east-2.amazoncognito.com/oauth2/idpresponse/,https://dailykpop63b1ff97-63b1ff97-dev.auth.us-east-2.amazoncognito.com/",
        "redirectSignOut": "dailykpop://callback/,exp://127.0.0.1:19000/--/,dailykpop://signout/,https://dailykpop63b1ff97-63b1ff97-dev.auth.us-east-2.amazoncognito.com/oauth2/idpresponse/,https://dailykpop63b1ff97-63b1ff97-dev.auth.us-east-2.amazoncognito.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
